In [6]:
import os

print(os.path.exists(r"E:\climate_risk_data_analysis"))

True

In [7]:
import os

print(os.listdir(r"E:\climate_risk_data_analysis"))

['climate-risk-index-1.csv', 'resource_links.md']

In [8]:
import pandas as pd
import numpy as np

# Load the climate risk dataset
df = pd.read_csv(
    r"E:\climate_risk_data_analysis\climate-risk-index-1.csv"
)

# Display the first 5 rows
df.head()

,index,cartodb_id,the_geom,the_geom_webmercator,country,cri_rank,cri_score,fatalities_per_100k_rank,fatalities_per_100k_total,fatalities_rank,fatalities_total,losses_per_gdp__rank,losses_per_gdp__total,losses_usdm_ppp_rank,losses_usdm_ppp_total,rw_country_code,rw_country_name
0,0,1,NaN,NaN,Saudi Arabia,79,72.50,18,0.45,18,140,131,0.0001,119,1.229,SAU,Saudi Arabia
1,1,2,NaN,NaN,Romania,61,61.50,112,0.01,102,1,16,0.6746,11,2797.884,ROU,Romania
2,2,3,NaN,NaN,Spain,69,66.33,74,0.05,47,22,86,0.0394,31,637.070,ESP,Spain
3,3,4,NaN,NaN,Slovenia,135,124.50,114,0.00,114,0,135,NaN,135,0.000,SVN,Slovenia
4,4,5,NaN,NaN,South Sudan,133,117.33,114,0.00,114,0,120,0.0021,122,0.508,SSD,South Sudan

In [9]:
# Dataset shape
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 182
Columns: 17

In [10]:
# Column names
df.columns.tolist()

['index',
 'cartodb_id',
 'the_geom',
 'the_geom_webmercator',
 'country',
 'cri_rank',
 'cri_score',
 'fatalities_per_100k_rank',
 'fatalities_per_100k_total',
 'fatalities_rank',
 'fatalities_total',
 'losses_per_gdp__rank',
 'losses_per_gdp__total',
 'losses_usdm_ppp_rank',
 'losses_usdm_ppp_total',
 'rw_country_code',
 'rw_country_name']

In [11]:
# Data types and non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   index                      182 non-null    int64
 1   cartodb_id                 182 non-null    int64
 2   the_geom                   0 non-null      float64
 3   the_geom_webmercator       0 non-null      float64
 4   country                    182 non-null    object
 5   cri_rank                   182 non-null    int64
 6   cri_score                  182 non-null    float64
 7   fatalities_per_100k_rank   182 non-null    int64
 8   fatalities_per_100k_total  182 non-null    float64
 9   fatalities_rank            182 non-null    int64
 10  fatalities_total           182 non-null    int64
 11  losses_per_gdp__rank       182 non-null    int64
 12  losses_per_gdp__total      131 non-null    float64
 13  losses_usdm_ppp_rank       182 non-null    int64
 14  losses_usdm_ppp_total      182 non-null    float64
 15  rw_country_code            179 non-null    object
 16  rw_country_name            179 non-null    object
dtypes: float64(6), int64(8), object(3)
memory usage: 24.3+ KB

In [12]:
# Missing values
df.isnull().sum()

index                          0
cartodb_id                     0
the_geom                     182
the_geom_webmercator         182
country                        0
cri_rank                       0
cri_score                      0
fatalities_per_100k_rank       0
fatalities_per_100k_total      0
fatalities_rank                0
fatalities_total               0
losses_per_gdp__rank           0
losses_per_gdp__total         51
losses_usdm_ppp_rank           0
losses_usdm_ppp_total          0
rw_country_code                3
rw_country_name                3
dtype: int64

In [13]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [14]:
missing = df.isnull().sum()

missing_df = pd.DataFrame({
    "Column": missing.index,
    "Missing Values": missing.values,
    "Missing %": (missing.values / len(df) * 100).round(2)
})

missing_df[missing_df["Missing Values"] > 0]

                   Column  Missing Values  Missing %
2                the_geom             182     100.00
3    the_geom_webmercator             182     100.00
12  losses_per_gdp__total              51      28.02
15        rw_country_code               3       1.65
16        rw_country_name               3       1.65

In [15]:
empty_columns = df.columns[df.isnull().all()]

print("Completely empty columns:")
print(empty_columns.tolist())

Completely empty columns:
['the_geom', 'the_geom_webmercator']

In [16]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [17]:
print("Country column:")
print(df["country"].unique())

print("\nResource Watch country name:")
print(df["rw_country_name"].unique())

Country column:
['Saudi Arabia' 'Romania' 'Spain' 'Slovenia' 'South Sudan' 'Sierra Leone'
 'South Africa' 'Serbia' 'Slovak Republic' 'Solomon Islands' 'Swaziland'
 'Turkey' 'Tanzania' 'Tunisia' 'Thailand' 'The Bahamas' 'Uganda' 'Vietnam'
 'United Kingdom' 'Uruguay' 'Venezuela' 'United States' 'Vanuatu'
 'United Arab Emirates' 'Ukraine' 'Bolivia' 'Belgium' "Cote d'Ivoire"
 'Croatia' 'Sri Lanka' 'Ecuador' 'Egypt' 'Sweden' 'Moldova' 'Mauritania'
 'Mexico' 'Singapore' 'Suriname' 'Azerbaijan' 'Australia' 'Angola'
 'Greece' 'Guyana' 'Guinea' 'Honduras' 'Ghana' 'Hungary'
 'Islamic Republic of Iran' 'Iraq' 'Indonesia' 'Italy' 'Ireland'
 'Antigua and Barbuda' 'Albania' 'Algeria' 'Austria' 'Argentina' 'Bahrain'
 'Belarus' 'Barbados' 'Bosnia and Herzegovina' 'Benin' 'Cambodia' 'Canada'
 'Central African Republic' 'Bulgaria' 'Brazil' 'Burkina Faso' 'Cameroon'
 'China' 'Chad' 'Chile' 'Colombia' 'Denmark'
 'Democratic Republic of Congo' 'Dominican Republic' 'Czech Republic'
 'Finland' 'Estonia' 'Ethiopia' 'Gabon' 'Fiji' 'Germany' 'Eritrea'
 'Georgia' 'France' 'Guinea-Bissau' 'Afghanistan' 'Iceland' 'India'
 'Kenya' 'Lao People’s Democratic Republic' 'Republic of Korea'
 'Kazakhstan' 'Kyrgyz Republic' 'Japan' 'Kiribati' 'Latvia' 'Lithuania'
 'Malawi' 'Libya' 'Madagascar' 'Malaysia' 'Liberia' 'Malta' 'Mali'
 'Netherlands' 'Nigeria' 'Morocco' 'Nicaragua' 'Niger' 'New Zealand'
 'Poland' 'Norway' 'Papua New Guinea' 'Portugal' 'Peru' 'Pakistan'
 'Panama' 'Paraguay' 'Republic of Congo' 'Republic of Yemen' 'Senegal'
 'Russia' 'Bhutan' 'Uzbekistan' 'Zambia' 'Zimbabwe' 'Armenia' 'Botswana'
 'Bangladesh' 'Belize' 'Cape Verde' 'Brunei Darussalam' 'Burundi'
 'Comoros' 'Cyprus' 'Dominica' 'Saint Vincent and the Grenadines' 'Taiwan'
 'Costa Rica' 'St. Lucia' 'Switzerland' 'Sudan' 'Djibouti' 'Jamaica'
 'Democratic Republic of Timor-Leste' 'Luxembourg' 'El Salvador'
 'St. Kitts and Nevis' 'Tajikistan'
 'Former Yugoslav Republic of Macedonia' 'Grenada' 'Haiti' 'Guatemala'
 'Israel' 'Jordan' 'Tuvalu' 'Kuwait' 'Micronesia' 'Kosovo' 'Mauritius'
 'Mongolia' 'Nepal' 'Namibia' 'Mozambique' 'Myanmar' 'Philippines' 'Oman'
 'Lesotho' 'Lebanon' 'Marshall Islands' 'Montenegro' 'Rwanda' 'Qatar'
 'Puerto Rico' 'Samoa' 'Seychelles' 'Gambia' 'Togo' 'Trinidad and Tobago'
 'Tonga']

Resource Watch country name:
['Saudi Arabia' 'Romania' 'Spain' 'Slovenia' 'South Sudan' 'Sierra Leone'
 'South Africa' 'Republic of Serbia' 'Slovakia' 'Solomon Islands'
 'Swaziland' 'Turkey' 'United Republic of Tanzania' 'Tunisia' 'Thailand'
 'The Bahamas' 'Uganda' 'Vietnam' 'United Kingdom' 'Uruguay' 'Venezuela'
 'United States of America' 'Vanuatu' 'United Arab Emirates' 'Ukraine'
 'Bolivia' 'Belgium' 'Ivory Coast' 'Croatia' 'Sri Lanka' 'Ecuador' 'Egypt'
 'Sweden' 'Moldova' 'Mauritania' 'Mexico' 'Singapore' 'Suriname'
 'Azerbaijan' 'Australia' 'Angola' 'Greece' 'Guyana' 'Guinea' 'Honduras'
 'Ghana' 'Hungary' 'Iran' 'Iraq' 'Indonesia' 'Italy' 'Ireland'
 'Antigua and Barbuda' 'Albania' 'Algeria' 'Austria' 'Argentina' 'Bahrain'
 'Belarus' 'Barbados' 'Bosnia and Herzegovina' 'Benin' 'Cambodia' 'Canada'
 'Central African Republic' 'Bulgaria' 'Brazil' 'Burkina Faso' 'Cameroon'
 'China' 'Chad' 'Chile' 'Colombia' 'Denmark'
 'Democratic Republic of the Congo' 'Dominican Republic' 'Czech Republic'
 'Finland' 'Estonia' 'Ethiopia' 'Gabon' 'Fiji' 'Germany' 'Eritrea'
 'Georgia' 'France' 'Guinea Bissau' 'Afghanistan' 'Iceland' 'India'
 'Kenya' 'Laos' 'South Korea' 'Kazakhstan' 'Kyrgyzstan' 'Japan' 'Kiribati'
 'Latvia' 'Lithuania' 'Malawi' 'Libya' 'Madagascar' 'Malaysia' 'Liberia'
 'Malta' 'Mali' 'Netherlands' 'Nigeria' 'Morocco' 'Nicaragua' 'Niger'
 'New Zealand' 'Poland' 'Norway' 'Papua New Guinea' 'Portugal' 'Peru'
 'Pakistan' 'Panama' 'Paraguay' 'Republic of Congo' 'Yemen' 'Senegal'
 'Russia' 'Bhutan' 'Uzbekistan' 'Zambia' 'Zimbabwe' 'Armenia' 'Botswana'
 'Bangladesh' 'Belize' 'Cape Verde' 'Brunei' 'Burundi' 'Comoros' 'Cyprus'
 'Dominica' 'Saint Vincent and the Grenadines' nan 'Costa Rica'
 'Saint Lucia' 'Switzerland' 'Sudan' 'Djibouti' 'Jamaica' 'Timor-Leste'
 'Luxembourg' 'El Salvador' 'Saint Kitts and Nevis' 'Tajikistan'
 'Macedonia' 'Grenada' 'Haiti' 'Guatemala' 'Israel' 'Jordan' 'Tuvalu'
 'Kuwait' 'Federated States of Micronesia' 'Mauritius' 'Mongolia' 'Nepal'
 'Namibia' 'Mozambique' 'Myanmar' 'Philippines' 'Oman' 'Lesotho' 'Lebanon'
 'Marshall Islands' 'Montenegro' 'Rwanda' 'Qatar' 'Samoa' 'Seychelles'
 'Gambia' 'Togo' 'Trinidad and Tobago' 'Tonga']

In [18]:
df = df.dropna(axis=1, how="all")

print("New shape:", df.shape)

New shape: (182, 15)

In [19]:
df = df.drop_duplicates()

print("New shape:", df.shape)

New shape: (182, 15)

In [20]:
df[["country", "rw_country_name", "rw_country_code"]].head(10)

           country     rw_country_name rw_country_code
0     Saudi Arabia        Saudi Arabia             SAU
1          Romania             Romania             ROU
2            Spain               Spain             ESP
3         Slovenia            Slovenia             SVN
4      South Sudan         South Sudan             SSD
5     Sierra Leone        Sierra Leone             SLE
6     South Africa        South Africa             ZAF
7           Serbia  Republic of Serbia             SRB
8  Slovak Republic            Slovakia             SVK
9  Solomon Islands     Solomon Islands             SLB

In [21]:
print("Country missing:", df["country"].isnull().sum())
print("RW country name missing:", df["rw_country_name"].isnull().sum())
print("RW country code missing:", df["rw_country_code"].isnull().sum())

Country missing: 0
RW country name missing: 3
RW country code missing: 3

In [22]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
index,182.0,90.500000,52.683014,0.0000,45.2500,90.5000,135.75000,181.0000
cartodb_id,182.0,91.500000,52.683014,1.0000,46.2500,91.5000,136.75000,182.0000
cri_rank,182.0,85.230769,44.708529,1.0000,46.2500,91.0000,135.00000,135.0000
cri_score,182.0,81.791923,34.582412,12.1700,52.8725,77.5000,124.50000,124.5000
fatalities_per_100k_rank,182.0,78.609890,37.858511,1.0000,46.2500,91.5000,114.00000,114.0000
fatalities_per_100k_total,182.0,0.519670,3.393934,0.0000,0.0000,0.0200,0.12000,43.6600
fatalities_rank,182.0,77.626374,37.500688,1.0000,46.2500,90.0000,114.00000,114.0000
fatalities_total,182.0,86.840659,427.350623,0.0000,0.0000,2.0000,22.75000,4317.0000
losses_per_gdp__rank,182.0,85.302198,44.691600,1.0000,46.2500,91.5000,135.00000,135.0000
losses_per_gdp__total,131.0,1.517654,8.171267,0.0001,0.0165,0.0841,0.27595,77.3694
losses_usdm_ppp_rank,182.0,85.302198,44.691600,1.0000,46.2500,91.5000,135.00000,135.0000
losses_usdm_ppp_total,182.0,907.507599,4483.998505,0.0000,0.0000,30.3470,262.17825,40077.2220

In [23]:
df.dtypes

index                          int64
cartodb_id                     int64
country                       object
cri_rank                       int64
cri_score                    float64
fatalities_per_100k_rank       int64
fatalities_per_100k_total    float64
fatalities_rank                int64
fatalities_total               int64
losses_per_gdp__rank           int64
losses_per_gdp__total        float64
losses_usdm_ppp_rank           int64
losses_usdm_ppp_total        float64
rw_country_code               object
rw_country_name               object
dtype: object

In [24]:
numeric_columns = df.select_dtypes(include=np.number).columns

print("Numeric columns:")
print(numeric_columns.tolist())

Numeric columns:
['index', 'cartodb_id', 'cri_rank', 'cri_score', 'fatalities_per_100k_rank', 'fatalities_per_100k_total', 'fatalities_rank', 'fatalities_total', 'losses_per_gdp__rank', 'losses_per_gdp__total', 'losses_usdm_ppp_rank', 'losses_usdm_ppp_total']

In [25]:
numeric_columns = [
    "cri_rank",
    "cri_score",
    "fatalities_per_100k_rank",
    "fatalities_per_100k_total",
    "fatalities_rank",
    "fatalities_total",
    "losses_per_gdp__rank",
    "losses_per_gdp__total",
    "losses_usdm_ppp_rank",
    "losses_usdm_ppp_total"
]

df[numeric_columns].min()

cri_rank                      1.0000
cri_score                    12.1700
fatalities_per_100k_rank      1.0000
fatalities_per_100k_total     0.0000
fatalities_rank               1.0000
fatalities_total              0.0000
losses_per_gdp__rank          1.0000
losses_per_gdp__total         0.0001
losses_usdm_ppp_rank          1.0000
losses_usdm_ppp_total         0.0000
dtype: float64

In [26]:
country_duplicates = df[df.duplicated(
    subset=["country"],
    keep=False
)]

country_duplicates[["country", "cri_rank", "cri_score"]]

Empty DataFrame
Columns: [country, cri_rank, cri_score]
Index: []

In [27]:
df["cri_score"].describe()

count    182.000000
mean      81.791923
std       34.582412
min       12.170000
25%       52.872500
50%       77.500000
75%      124.500000
max      124.500000
Name: cri_score, dtype: float64

In [28]:
df[["country", "cri_rank", "cri_score"]].sort_values(
    "cri_rank"
).head(10)

         country  cri_rank  cri_score
165   Mozambique         1      12.17
137     Dominica         2      13.00
99        Malawi         3      13.83
89         India         4      15.33
22       Vanuatu         5      20.33
166      Myanmar         6      20.83
15   The Bahamas         7      22.83
101   Madagascar         8      23.33
45         Ghana         8      23.33
71         Chile        10      25.17

In [29]:
df[["country", "cri_rank", "cri_score"]].sort_values(
    "cri_rank"
).head(10)

         country  cri_rank  cri_score
165   Mozambique         1      12.17
137     Dominica         2      13.00
99        Malawi         3      13.83
89         India         4      15.33
22       Vanuatu         5      20.33
166      Myanmar         6      20.83
15   The Bahamas         7      22.83
101   Madagascar         8      23.33
45         Ghana         8      23.33
71         Chile        10      25.17

In [30]:
columns_to_drop = [
    "index",
    "cartodb_id",
    "the_geom",
    "the_geom_webmercator"
]

df_clean = df.drop(columns=columns_to_drop, errors="ignore")

print("Shape after removing unnecessary columns:", df_clean.shape)

Shape after removing unnecessary columns: (182, 13)

In [31]:
df_clean = df_clean.rename(columns={
    "cri_rank": "CRI_Rank",
    "cri_score": "CRI_Score",
    "fatalities_per_100k_rank": "Fatalities_Per_100K_Rank",
    "fatalities_per_100k_total": "Fatalities_Per_100K",
    "fatalities_rank": "Fatalities_Rank",
    "fatalities_total": "Total_Fatalities",
    "losses_per_gdp__rank": "Losses_Per_GDP_Rank",
    "losses_per_gdp__total": "Losses_Per_GDP_Pct",
    "losses_usdm_ppp_rank": "Economic_Loss_Rank",
    "losses_usdm_ppp_total": "Economic_Loss_USD_Mn_PPP",
    "rw_country_code": "Country_Code",
    "rw_country_name": "RW_Country_Name"
})

df_clean.head()

,country,CRI_Rank,CRI_Score,Fatalities_Per_100K_Rank,Fatalities_Per_100K,Fatalities_Rank,Total_Fatalities,Losses_Per_GDP_Rank,Losses_Per_GDP_Pct,Economic_Loss_Rank,Economic_Loss_USD_Mn_PPP,Country_Code,RW_Country_Name
0,Saudi Arabia,79,72.50,18,0.45,18,140,131,0.0001,119,1.229,SAU,Saudi Arabia
1,Romania,61,61.50,112,0.01,102,1,16,0.6746,11,2797.884,ROU,Romania
2,Spain,69,66.33,74,0.05,47,22,86,0.0394,31,637.070,ESP,Spain
3,Slovenia,135,124.50,114,0.00,114,0,135,NaN,135,0.000,SVN,Slovenia
4,South Sudan,133,117.33,114,0.00,114,0,120,0.0021,122,0.508,SSD,South Sudan

In [32]:
text_columns = [
    "country",
    "Country_Code",
    "RW_Country_Name"
]

for col in text_columns:
    if col in df_clean.columns:
        df_clean[col] = df_clean[col].astype("string").str.strip()

In [33]:
print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])

print("\nColumns:")
print(df_clean.columns.tolist())

Rows: 182
Columns: 13

Columns:
['country', 'CRI_Rank', 'CRI_Score', 'Fatalities_Per_100K_Rank', 'Fatalities_Per_100K', 'Fatalities_Rank', 'Total_Fatalities', 'Losses_Per_GDP_Rank', 'Losses_Per_GDP_Pct', 'Economic_Loss_Rank', 'Economic_Loss_USD_Mn_PPP', 'Country_Code', 'RW_Country_Name']

In [34]:
df_clean.isnull().sum()

country                      0
CRI_Rank                     0
CRI_Score                    0
Fatalities_Per_100K_Rank     0
Fatalities_Per_100K          0
Fatalities_Rank              0
Total_Fatalities             0
Losses_Per_GDP_Rank          0
Losses_Per_GDP_Pct          51
Economic_Loss_Rank           0
Economic_Loss_USD_Mn_PPP     0
Country_Code                 3
RW_Country_Name              3
dtype: int64

In [35]:
missing_rows = df_clean[df_clean.isnull().any(axis=1)]

missing_rows

,country,CRI_Rank,CRI_Score,Fatalities_Per_100K_Rank,Fatalities_Per_100K,Fatalities_Rank,Total_Fatalities,Losses_Per_GDP_Rank,Losses_Per_GDP_Pct,Economic_Loss_Rank,Economic_Loss_USD_Mn_PPP,Country_Code,RW_Country_Name
3,Slovenia,135,124.50,114,0.00,114,0,135,NaN,135,0.000,SVN,Slovenia
13,Tunisia,135,124.50,114,0.00,114,0,135,NaN,135,0.000,TUN,Tunisia
20,Venezuela,135,124.50,114,0.00,114,0,135,NaN,135,0.000,VEN,Venezuela
23,United Arab Emirates,127,109.17,86,0.03,85,3,133,NaN,132,0.087,ARE,United Arab Emirates
34,Mauritania,135,124.50,114,0.00,114,0,135,NaN,135,0.000,MRT,Mauritania
36,Singapore,135,124.50,114,0.00,114,0,135,NaN,135,0.000,SGP,Singapore
37,Suriname,135,124.50,114,0.00,114,0,135,NaN,135,0.000,SUR,Suriname
38,Azerbaijan,135,124.50,114,0.00,114,0,135,NaN,135,0.000,AZE,Azerbaijan
42,Guyana,135,124.50,114,0.00,114,0,135,NaN,135,0.000,GUY,Guyana
52,Antigua and Barbuda,135,124.50,114,0.00,114,0,135,NaN,135,0.000,ATG,Antigua and Barbuda
57,Bahrain,135,124.50,114,0.00,114,0,135,NaN,135,0.000,BHR,Bahrain
58,Belarus,135,124.50,114,0.00,114,0,135,NaN,135,0.000,BLR,Belarus
59,Barbados,135,124.50,114,0.00,114,0,135,NaN,135,0.000,BRB,Barbados
61,Benin,135,124.50,114,0.00,114,0,135,NaN,135,0.000,BEN,Benin
64,Central African Republic,135,124.50,114,0.00,114,0,135,NaN,135,0.000,CAF,Central African Republic
70,Chad,135,124.50,114,0.00,114,0,135,NaN,135,0.000,TCD,Chad
77,Finland,135,124.50,114,0.00,114,0,135,NaN,135,0.000,FIN,Finland
78,Estonia,135,124.50,114,0.00,114,0,135,NaN,135,0.000,EST,Estonia
80,Gabon,135,124.50,114,0.00,114,0,135,NaN,135,0.000,GAB,Gabon
83,Eritrea,135,124.50,114,0.00,114,0,135,NaN,135,0.000,ERI,Eritrea
92,Republic of Korea,135,124.50,114,0.00,114,0,135,NaN,135,0.000,KOR,South Korea
97,Latvia,135,124.50,114,0.00,114,0,135,NaN,135,0.000,LVA,Latvia
98,Lithuania,135,124.50,114,0.00,114,0,135,NaN,135,0.000,LTU,Lithuania
100,Libya,135,124.50,114,0.00,114,0,135,NaN,135,0.000,LBY,Libya
102,Malaysia,132,117.00,111,0.01,90,2,132,NaN,126,0.276,MYS,Malaysia
104,Malta,135,124.50,114,0.00,114,0,135,NaN,135,0.000,MLT,Malta
108,Morocco,134,121.50,113,0.00,102,1,134,NaN,133,0.027,MAR,Morocco
125,Uzbekistan,135,124.50,114,0.00,114,0,135,NaN,135,0.000,UZB,Uzbekistan
131,Belize,135,124.50,114,0.00,114,0,135,NaN,135,0.000,BLZ,Belize
133,Brunei Darussalam,135,124.50,114,0.00,114,0,135,NaN,135,0.000,BRN,Brunei
135,Comoros,135,124.50,114,0.00,114,0,135,NaN,135,0.000,COM,Comoros
136,Cyprus,135,124.50,114,0.00,114,0,135,NaN,135,0.000,CYP,Cyprus
138,Saint Vincent and the Grenadines,135,124.50,114,0.00,114,0,135,NaN,135,0.000,VCT,Saint Vincent and the Grenadines
139,Taiwan,51,56.17,75,0.05,65,11,53,0.1338,16,1472.523,<NA>,<NA>
141,St. Lucia,135,124.50,114,0.00,114,0,135,NaN,135,0.000,LCA,Saint Lucia
144,Djibouti,135,124.50,114,0.00,114,0,135,NaN,135,0.000,DJI,Djibouti
145,Jamaica,135,124.50,114,0.00,114,0,135,NaN,135,0.000,JAM,Jamaica
146,Democratic Republic of Timor-Leste,135,124.50,114,0.00,114,0,135,NaN,135,0.000,TLS,Timor-Leste
147,Luxembourg,135,124.50,114,0.00,114,0,135,NaN,135,0.000,LUX,Luxembourg
149,St. Kitts and Nevis,135,124.50,114,0.00,114,0,135,NaN,135,0.000,KNA,Saint Kitts and Nevis
152,Grenada,135,124.50,114,0.00,114,0,135,NaN,135,0.000,GRD,Grenada
158,Kuwait,135,124.50,114,0.00,114,0,135,NaN,135,0.000,KWT,Kuwait
160,Kosovo,135,124.50,114,0.00,114,0,135,NaN,135,0.000,<NA>,<NA>
161,Mauritius,135,124.50,114,0.00,114,0,135,NaN,135,0.000,MUS,Mauritius
169,Lesotho,135,124.50,114,0.00,114,0,135,NaN,135,0.000,LSO,Lesotho
171,Marshall Islands,135,124.50,114,0.00,114,0,135,NaN,135,0.000,MHL,Marshall Islands
172,Montenegro,135,124.50,114,0.00,114,0,135,NaN,135,0.000,MNE,Montenegro
175,Puerto Rico,110,97.00,114,0.00,114,0,81,0.0437,78,57.565,<NA>,<NA>
176,Samoa,135,124.50,114,0.00,114,0,135,NaN,135,0.000,WSM,Samoa
177,Seychelles,135,124.50,114,0.00,114,0,135,NaN,135,0.000,SYC,Seychelles
178,Gambia,135,124.50,114,0.00,114,0,135,NaN,135,0.000,GMB,Gambia
180,Trinidad and Tobago,135,124.50,114,0.00,114,0,135,NaN,135,0.000,TTO,Trinidad and Tobago
181,Tonga,135,124.50,114,0.00,114,0,135,NaN,135,0.000,TON,Tonga

In [36]:
df_clean[
    df_clean["country"].isnull() |
    df_clean["Country_Code"].isnull() |
    df_clean["RW_Country_Name"].isnull()
][[
    "country",
    "Country_Code",
    "RW_Country_Name",
    "CRI_Rank",
    "CRI_Score"
]]

         country Country_Code RW_Country_Name  CRI_Rank  CRI_Score
139       Taiwan         <NA>            <NA>        51      56.17
160       Kosovo         <NA>            <NA>       135     124.50
175  Puerto Rico         <NA>            <NA>       110      97.00

In [37]:
df_clean[
    df_clean["Losses_Per_GDP_Pct"].isnull()
][[
    "country",
    "CRI_Rank",
    "CRI_Score",
    "Economic_Loss_USD_Mn_PPP",
    "Losses_Per_GDP_Pct"
]]

,country,CRI_Rank,CRI_Score,Economic_Loss_USD_Mn_PPP,Losses_Per_GDP_Pct
3,Slovenia,135,124.50,0.000,NaN
13,Tunisia,135,124.50,0.000,NaN
20,Venezuela,135,124.50,0.000,NaN
23,United Arab Emirates,127,109.17,0.087,NaN
34,Mauritania,135,124.50,0.000,NaN
36,Singapore,135,124.50,0.000,NaN
37,Suriname,135,124.50,0.000,NaN
38,Azerbaijan,135,124.50,0.000,NaN
42,Guyana,135,124.50,0.000,NaN
52,Antigua and Barbuda,135,124.50,0.000,NaN
57,Bahrain,135,124.50,0.000,NaN
58,Belarus,135,124.50,0.000,NaN
59,Barbados,135,124.50,0.000,NaN
61,Benin,135,124.50,0.000,NaN
64,Central African Republic,135,124.50,0.000,NaN
70,Chad,135,124.50,0.000,NaN
77,Finland,135,124.50,0.000,NaN
78,Estonia,135,124.50,0.000,NaN
80,Gabon,135,124.50,0.000,NaN
83,Eritrea,135,124.50,0.000,NaN
92,Republic of Korea,135,124.50,0.000,NaN
97,Latvia,135,124.50,0.000,NaN
98,Lithuania,135,124.50,0.000,NaN
100,Libya,135,124.50,0.000,NaN
102,Malaysia,132,117.00,0.276,NaN
104,Malta,135,124.50,0.000,NaN
108,Morocco,134,121.50,0.027,NaN
125,Uzbekistan,135,124.50,0.000,NaN
131,Belize,135,124.50,0.000,NaN
133,Brunei Darussalam,135,124.50,0.000,NaN
135,Comoros,135,124.50,0.000,NaN
136,Cyprus,135,124.50,0.000,NaN
138,Saint Vincent and the Grenadines,135,124.50,0.000,NaN
141,St. Lucia,135,124.50,0.000,NaN
144,Djibouti,135,124.50,0.000,NaN
145,Jamaica,135,124.50,0.000,NaN
146,Democratic Republic of Timor-Leste,135,124.50,0.000,NaN
147,Luxembourg,135,124.50,0.000,NaN
149,St. Kitts and Nevis,135,124.50,0.000,NaN
152,Grenada,135,124.50,0.000,NaN
158,Kuwait,135,124.50,0.000,NaN
160,Kosovo,135,124.50,0.000,NaN
161,Mauritius,135,124.50,0.000,NaN
169,Lesotho,135,124.50,0.000,NaN
171,Marshall Islands,135,124.50,0.000,NaN
172,Montenegro,135,124.50,0.000,NaN
176,Samoa,135,124.50,0.000,NaN
177,Seychelles,135,124.50,0.000,NaN
178,Gambia,135,124.50,0.000,NaN
180,Trinidad and Tobago,135,124.50,0.000,NaN
181,Tonga,135,124.50,0.000,NaN

In [38]:
df_clean[
    (df_clean["CRI_Score"] < 0) |
    (df_clean["Total_Fatalities"] < 0) |
    (df_clean["Fatalities_Per_100K"] < 0) |
    (df_clean["Economic_Loss_USD_Mn_PPP"] < 0)
]

Empty DataFrame
Columns: [country, CRI_Rank, CRI_Score, Fatalities_Per_100K_Rank, Fatalities_Per_100K, Fatalities_Rank, Total_Fatalities, Losses_Per_GDP_Rank, Losses_Per_GDP_Pct, Economic_Loss_Rank, Economic_Loss_USD_Mn_PPP, Country_Code, RW_Country_Name]
Index: []

In [39]:
df_clean["country"] = df_clean["country"].fillna(
    df_clean["RW_Country_Name"]
)

In [40]:
df_clean["Country_Code"] = df_clean["Country_Code"].replace(
    ["", " ", "nan", "None"],
    pd.NA
)

In [41]:
df_clean = df_clean.drop(columns=["RW_Country_Name"])

In [42]:
numeric_columns = [
    "CRI_Rank",
    "CRI_Score",
    "Fatalities_Per_100K_Rank",
    "Fatalities_Per_100K",
    "Fatalities_Rank",
    "Total_Fatalities",
    "Losses_Per_GDP_Rank",
    "Losses_Per_GDP_Pct",
    "Economic_Loss_Rank",
    "Economic_Loss_USD_Mn_PPP"
]

for col in numeric_columns:
    df_clean[col] = pd.to_numeric(
        df_clean[col],
        errors="coerce"
    )

In [43]:
print("Final shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicate rows:")
print(df_clean.duplicated().sum())

print("\nData types:")
print(df_clean.dtypes)

Final shape: (182, 12)

Missing values:
country                      0
CRI_Rank                     0
CRI_Score                    0
Fatalities_Per_100K_Rank     0
Fatalities_Per_100K          0
Fatalities_Rank              0
Total_Fatalities             0
Losses_Per_GDP_Rank          0
Losses_Per_GDP_Pct          51
Economic_Loss_Rank           0
Economic_Loss_USD_Mn_PPP     0
Country_Code                 3
dtype: int64

Duplicate rows:
0

Data types:
country                     string[python]
CRI_Rank                             int64
CRI_Score                          float64
Fatalities_Per_100K_Rank             int64
Fatalities_Per_100K                float64
Fatalities_Rank                      int64
Total_Fatalities                     int64
Losses_Per_GDP_Rank                  int64
Losses_Per_GDP_Pct                 float64
Economic_Loss_Rank                   int64
Economic_Loss_USD_Mn_PPP           float64
Country_Code                string[python]
dtype: object

In [44]:
output_path = r"E:\climate_risk_data_analysis\climate_risk_cleaned.csv"

df_clean.to_csv(
    output_path,
    index=False
)

print("Cleaned dataset saved successfully!")
print(output_path)

Cleaned dataset saved successfully!
E:\climate_risk_data_analysis\climate_risk_cleaned.csv

In [45]:
print(df_clean.columns.tolist())

['country', 'CRI_Rank', 'CRI_Score', 'Fatalities_Per_100K_Rank', 'Fatalities_Per_100K', 'Fatalities_Rank', 'Total_Fatalities', 'Losses_Per_GDP_Rank', 'Losses_Per_GDP_Pct', 'Economic_Loss_Rank', 'Economic_Loss_USD_Mn_PPP', 'Country_Code']

In [1]:
import pandas as pd

df_clean = pd.read_csv(
    r"E:\climate_risk_data_analysis\climate_risk_cleaned.csv"
)

print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))

Rows: 182
Columns: 12